build(website): use vite-react_ssg
childrentime/reactuse pull request #51
Opened 2023-07-31 11:31 UTC by Daydreamer-riri

2023-07-31 12:11 UTC, childrentime commented
@Daydreamer-riri HI, it breaks netlify and lint

2023-07-31 12:16 UTC, Daydreamer-riri commented
I got it. I will fix these problems tomorrow.

2023-07-31 12:21 UTC, childrentime commented
@Daydreamer-riri It seems file. and we need remove the comment in css.

2023-07-31 12:21 UTC, childrentime commented on packages/website/package.json
lint

2023-07-31 12:22 UTC, childrentime requested changes

2023-07-31 12:22 UTC, childrentime commented on packages/website/src/main.css
remove comments

2023-08-01 03:26 UTC, childrentime submitted a review, later dismissed

2023-08-01 03:27 UTC, childrentime commented
@Daydreamer-riri Are there any other changes need to commit?

2023-08-01 03:48 UTC, Daydreamer-riri commented
That's all.

2023-08-01 03:54 UTC, childrentime approved these changes

2023-08-01 03:54 UTC, merged